### ISSUE TITLE
Calendar not legible in Bootstrap 5 dark mode (data-bs-theme="dark")

### ISSUE THREAD

**Issue by pokerbeing** [monim67/django-bootstrap-datepicker-plus#109]
**Is your feature request related to a problem? Please describe.**
Bootstrap 5.3 now has a global data-bs-theme="dark" attribute.  However,  if the user invokes this dark-theme, the datepicker calendar is not very legible against the Bootstrap5 standard dark theme color scheme.   The gray Year and Month choices don't contrast enough with dark background.  (See screenshot)  

![Datepicker](https://github.com/monim67/django-bootstrap-datepicker-plus/assets/36057637/ab7259b5-3f5d-46b9-8c2b-5bf313b7c643)
It would be awesome if the datepicker calendar had a new corresponding dark mode color scheme that was more legible against the Bootstrap5 dark-theme background.  Then this style calendar could be triggered by the value of this attribute as either data-bs-theme="dark" or data-bs-theme="light"

**Describe the solution you'd like**
Based upon the attribute value in the <html> tag, the datepicker calendar will:
	<html lang="en" data-bs-theme="light">  - no effect
	<html lang="en" data-bs-theme="dark">   - change to a new dark-mode color scheme

**Describe alternatives you've considered**
None.

**Additional context**
See attached screenshot with Bootstrap5 in new dark mode.

**Comment by sanchimenea** [comment]
The following css makes dark mode work. 

```
  .bootstrap-datetimepicker-widget.dropdown-menu {
    background-color: var(--bs-dropdown-bg);
  }
  .bootstrap-datetimepicker-widget table td.day:hover,
  .bootstrap-datetimepicker-widget table td.hour:hover,
  .bootstrap-datetimepicker-widget table td.minute:hover,
  .bootstrap-datetimepicker-widget table td.second:hover {
    background: var(--bs-tertiary-bg);
    cursor: pointer;
  }
  .bootstrap-datetimepicker-widget table td span:hover {
    background: var(--bs-tertiary-bg);
  }
  .bootstrap-datetimepicker-widget table thead tr:first-child th:hover {
    background: var(--bs-tertiary-bg);
  }
}
```

**Comment by sanchimenea** [comment]
Adding the following css will make dark mode work. 

```css
// Bootstrap Datepicker Dark mode

[data-bs-theme=dark] .bootstrap-datetimepicker-widget.dropdown-menu {
    background-color: var(--bs-dropdown-bg)
}

[data-bs-theme=dark] .bootstrap-datetimepicker-widget table td.day:hover,
[data-bs-theme=dark] .bootstrap-datetimepicker-widget table td.hour:hover,
[data-bs-theme=dark] .bootstrap-datetimepicker-widget table td.minute:hover,
[data-bs-theme=dark] .bootstrap-datetimepicker-widget table td.second:hover {
    background: var(--bs-tertiary-bg);
    cursor: pointer
}

[data-bs-theme=dark] .bootstrap-datetimepicker-widget table td span:hover,
[data-bs-theme=dark] .bootstrap-datetimepicker-widget table thead tr:first-child th:hover {
    background: var(--bs-tertiary-bg)
}
```
